# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: activate python
      run: python -m venv venv 
    - name: Activate python 
      run: source venv/bin/activate
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./advinow/requirements/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install requirments
      
      run: |
          python -m pip install --upgrade pip
          pwd
          pip install -r ./requirements/requirements.txt
    - name: Initialize Alembic migrations
      run: |
        pwd
        cd ./app
        alembic init migrations
    - name: Update Alembic env.py target_metadata
      run: |
        ls
        sed -i '/^target_metadata *=/c\target_metadata = Base.metadata' ./app/migrations/env.py
        grep -q 'from models import Base' ./migrations/env.py || sed -i '1ifrom models import Base' ./app/migrations/env.py

      
